language: node_js
node_js:
  - 0.10
env:
  matrix:
    - VERSION=1.2
    - VERSION=1.3
  global:
    - BROWSER_PROVIDER_READY_FILE=/tmp/sauce-connect-ready
    - LOGS_DIR=/tmp/angular-hint-module-build/logs
    - SAUCE_USERNAME=angular-ci
    - SAUCE_ACCESS_KEY=9b988f434ff8-fbca-8aa4-4ae3-35442987

install:
  - npm install
  - npm install -g bower
  - ./bower-install.sh
  - npm install -g karma-cli
